/**
 * lib/teamNames.js
 * International (non-Arabic) team names indexed by slug.
 * Used in FR/EN league standing tables and team pages.
 */
export const teamIntlNames = {
  // Premier League
  "arsenal":            { en: "Arsenal",               fr: "Arsenal" },
  "aston-villa":        { en: "Aston Villa",           fr: "Aston Villa" },
  "brentford":          { en: "Brentford",             fr: "Brentford" },
  "brighton":           { en: "Brighton",              fr: "Brighton" },
  "chelsea":            { en: "Chelsea",               fr: "Chelsea" },
  "crystal-palace":     { en: "Crystal Palace",        fr: "Crystal Palace" },
  "everton":            { en: "Everton",               fr: "Everton" },
  "fulham":             { en: "Fulham",                fr: "Fulham" },
  "liverpool":          { en: "Liverpool",             fr: "Liverpool" },
  "manchester-city":    { en: "Manchester City",       fr: "Manchester City" },
  "manchester-united":  { en: "Manchester United",     fr: "Manchester United" },
  "newcastle":          { en: "Newcastle United",      fr: "Newcastle United" },
  "nottingham-forest":  { en: "Nottingham Forest",     fr: "Nottingham Forest" },
  "tottenham":          { en: "Tottenham Hotspur",     fr: "Tottenham" },
  "west-ham":           { en: "West Ham United",       fr: "West Ham" },
  "wolves":             { en: "Wolverhampton",         fr: "Wolverhampton" },
  // La Liga
  "real-madrid":        { en: "Real Madrid",           fr: "Real Madrid" },
  "barcelona":          { en: "FC Barcelona",          fr: "FC Barcelone" },
  "atletico-madrid":    { en: "Atlético Madrid",       fr: "Atlético Madrid" },
  "villarreal":         { en: "Villarreal CF",         fr: "Villarreal" },
  "real-betis":         { en: "Real Betis",            fr: "Real Betis" },
  "real-sociedad":      { en: "Real Sociedad",         fr: "Real Sociedad" },
  "athletic-bilbao":    { en: "Athletic Bilbao",       fr: "Athletic Bilbao" },
  "celta-vigo":         { en: "Celta Vigo",            fr: "Celta Vigo" },
  "sevilla":            { en: "Sevilla FC",            fr: "Séville" },
  "getafe":             { en: "Getafe CF",             fr: "Getafe" },
  "osasuna":            { en: "CA Osasuna",            fr: "Osasuna" },
  "girona":             { en: "Girona FC",             fr: "Girona" },
  "mallorca":           { en: "RCD Mallorca",          fr: "Majorque" },
  "rayo-vallecano":     { en: "Rayo Vallecano",        fr: "Rayo Vallecano" },
  "espanyol":           { en: "RCD Espanyol",          fr: "Espanyol" },
  "alaves":             { en: "Alavés",                fr: "Alavés" },
  "valencia":           { en: "Valencia CF",           fr: "Valence" },
  // Bundesliga
  "bayern-munich":      { en: "Bayern Munich",         fr: "Bayern Munich" },
  "borussia-dortmund":  { en: "Borussia Dortmund",    fr: "Borussia Dortmund" },
  "rb-leipzig":         { en: "RB Leipzig",            fr: "RB Leipzig" },
  "bayer-leverkusen":   { en: "Bayer Leverkusen",     fr: "Bayer Leverkusen" },
  "eintracht-frankfurt":{ en: "Eintracht Frankfurt",   fr: "Eintracht Francfort" },
  "vfb-stuttgart":      { en: "VfB Stuttgart",         fr: "Stuttgart" },
  "wolfsburg":          { en: "VfL Wolfsburg",         fr: "Wolfsburg" },
  "hoffenheim":         { en: "TSG Hoffenheim",        fr: "Hoffenheim" },
  "freiburg":           { en: "SC Freiburg",           fr: "Fribourg" },
  "mainz":              { en: "FSV Mainz 05",          fr: "Mayence" },
  "augsburg":           { en: "FC Augsburg",           fr: "Augsbourg" },
  "werder-bremen":      { en: "Werder Bremen",         fr: "Werder Brême" },
  "union-berlin":       { en: "Union Berlin",          fr: "Union Berlin" },
  "fc-koln":            { en: "FC Köln",               fr: "FC Cologne" },
  "heidenheim":         { en: "1. FC Heidenheim",      fr: "Heidenheim" },
  "st-pauli":           { en: "FC St. Pauli",          fr: "St. Pauli" },
  "hamburger-sv":       { en: "Hamburger SV",          fr: "Hambourg" },
  // Serie A
  "ac-milan":           { en: "AC Milan",              fr: "AC Milan" },
  "inter-miami":        { en: "Inter Miami",           fr: "Inter Miami" },
  "juventus":           { en: "Juventus",              fr: "Juventus" },
  "napoli":             { en: "Napoli",                fr: "Naples" },
  "as-roma":            { en: "AS Roma",               fr: "AS Rome" },
  "lazio":              { en: "SS Lazio",              fr: "Lazio" },
  "atalanta":           { en: "Atalanta BC",           fr: "Atalanta" },
  "fiorentina":         { en: "ACF Fiorentina",        fr: "Fiorentina" },
  "bologna":            { en: "Bologna FC",            fr: "Bologne" },
  "torino":             { en: "Torino FC",             fr: "Torino" },
  "genoa":              { en: "Genoa CFC",             fr: "Gênes" },
  "udinese":            { en: "Udinese Calcio",        fr: "Udinese" },
  "cagliari":           { en: "Cagliari Calcio",       fr: "Cagliari" },
  "lecce":              { en: "US Lecce",              fr: "Lecce" },
  "hellas-verona":      { en: "Hellas Verona",         fr: "Hellas Vérone" },
  "como":               { en: "Como 1907",             fr: "Côme" },
  "parma":              { en: "Parma Calcio",          fr: "Parme" },
  // Ligue 1
  "psg":                { en: "Paris Saint-Germain",   fr: "PSG" },
  "olympique-marseille":{ en: "Olympique Marseille",   fr: "OM" },
  "olympique-lyon":     { en: "Olympique Lyonnais",    fr: "OL" },
  "monaco":             { en: "AS Monaco",             fr: "Monaco" },
  "losc-lille":         { en: "LOSC Lille",            fr: "Lille" },
  "nice":               { en: "OGC Nice",              fr: "Nice" },
  "stade-rennes":       { en: "Stade Rennais",         fr: "Rennes" },
  "lens":               { en: "RC Lens",               fr: "Lens" },
  "toulouse":           { en: "Toulouse FC",           fr: "Toulouse" },
  "stade-brestois":     { en: "Stade Brestois 29",     fr: "Brest" },
  "nantes":             { en: "FC Nantes",             fr: "Nantes" },
  "strasbourg":         { en: "RC Strasbourg",         fr: "Strasbourg" },
  "le-havre":           { en: "Le Havre AC",           fr: "Le Havre" },
  "lorient":            { en: "FC Lorient",            fr: "Lorient" },
  "metz":               { en: "FC Metz",               fr: "Metz" },
  "angers":             { en: "Angers SCO",            fr: "Angers" },
  "auxerre":            { en: "AJ Auxerre",            fr: "Auxerre" },
  // Champions League extras
  "psv-eindhoven":      { en: "PSV Eindhoven",         fr: "PSV Eindhoven" },
  "az-alkmaar":         { en: "AZ Alkmaar",            fr: "AZ Alkmaar" },
  "fc-twente":          { en: "FC Twente",             fr: "FC Twente" },
  "fc-utrecht":         { en: "FC Utrecht",            fr: "FC Utrecht" },
  "sparta-rotterdam":   { en: "Sparta Rotterdam",      fr: "Sparta Rotterdam" },
  "fortuna-sittard":    { en: "Fortuna Sittard",       fr: "Fortuna Sittard" },
  "heracles":           { en: "Heracles Almelo",       fr: "Heracles" },
  "heerenveen":         { en: "SC Heerenveen",         fr: "Heerenveen" },
  "groningen":          { en: "FC Groningen",          fr: "Groningue" },
  "go-ahead-eagles":    { en: "Go Ahead Eagles",       fr: "Go Ahead Eagles" },
  "nac-breda":          { en: "NAC Breda",             fr: "NAC Breda" },
  "nec-nijmegen":       { en: "NEC Nijmegen",          fr: "NEC Nimègue" },
  "pec-zwolle":         { en: "PEC Zwolle",            fr: "PEC Zwolle" },
  "almere-city":        { en: "Almere City FC",        fr: "Almere City" },
  "benfica":            { en: "SL Benfica",            fr: "Benfica" },
  "porto":              { en: "FC Porto",              fr: "Porto" },
  "sporting-cp":        { en: "Sporting CP",           fr: "Sporting CP" },
  "braga":              { en: "SC Braga",              fr: "Braga" },
  "arouca":             { en: "FC Arouca",             fr: "Arouca" },
  "casa-pia":           { en: "Casa Pia AC",           fr: "Casa Pia" },
  "estoril":            { en: "Estoril Praia",         fr: "Estoril" },
  "famalicao":          { en: "FC Famalicão",          fr: "Famalicão" },
  "gil-vicente":        { en: "Gil Vicente FC",        fr: "Gil Vicente" },
  "moreirense":         { en: "Moreirense FC",         fr: "Moreirense" },
  "nacional":           { en: "CD Nacional",           fr: "Nacional" },
  "rio-ave":            { en: "Rio Ave FC",            fr: "Rio Ave" },
  // Saudi Pro League
  "al-hilal":           { en: "Al-Hilal",              fr: "Al-Hilal" },
  "al-nassr":           { en: "Al-Nassr",              fr: "Al-Nassr" },
  "al-ittihad":         { en: "Al-Ittihad",            fr: "Al-Ittihad" },
  "al-ahli":            { en: "Al-Ahli",               fr: "Al-Ahli" },
  "al-shabab":          { en: "Al-Shabab",             fr: "Al-Shabab" },
  "al-qadsiah":         { en: "Al-Qadsiah",            fr: "Al-Qadsiah" },
  "al-ettifaq":         { en: "Al-Ettifaq",            fr: "Al-Ettifaq" },
  "al-fateh":           { en: "Al-Fateh",              fr: "Al-Fateh" },
  "al-riyadh":          { en: "Al-Riyadh",             fr: "Al-Riyadh" },
  "al-fayha":           { en: "Al-Fayha",              fr: "Al-Fayha" },
  "al-hazm":            { en: "Al-Hazm",               fr: "Al-Hazm" },
  "al-kholood":         { en: "Al-Kholood",            fr: "Al-Kholood" },
  "al-okhdood":         { en: "Al-Okhdood",            fr: "Al-Okhdood" },
  "al-taawon":          { en: "Al-Taawon",             fr: "Al-Taawon" },
  "al-wahda":           { en: "Al-Wahda",              fr: "Al-Wahda" },
  "al-wehda":           { en: "Al-Wehda",              fr: "Al-Wehda" },
  "damac":              { en: "Damac FC",              fr: "Damac FC" },
  // MLS
  "atlanta-united":     { en: "Atlanta United",        fr: "Atlanta United" },
  "columbus-crew":      { en: "Columbus Crew",         fr: "Columbus Crew" },
  "fc-cincinnati":      { en: "FC Cincinnati",         fr: "FC Cincinnati" },
  "inter-miami":        { en: "Inter Miami CF",        fr: "Inter Miami" },
  "new-england-revolution": { en: "New England Revolution", fr: "New England Revolution" },
  "nycfc":              { en: "New York City FC",      fr: "New York City FC" },
  "philadelphia-union": { en: "Philadelphia Union",    fr: "Philadelphia Union" },
  "austin-fc":          { en: "Austin FC",             fr: "Austin FC" },
};

/**
 * Get international name for a team slug.
 * Returns { en, fr } or null if not found.
 */
export function getTeamIntlName(slug, lang = "en") {
  if (!slug) return null;
  return teamIntlNames[slug]?.[lang] || null;
}

/**
 * Display name: tries intl name first, falls back to Arabic name.
 * Used in FR/EN contexts.
 */
export function displayName(slug, arabicName, lang = "en") {
  return getTeamIntlName(slug, lang) || arabicName;
}
